# Generated by Django 3.2.20 on 2023-07-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, unique=True),
        ),
    ]
