# Generated by Django 3.2.20 on 2023-07-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0002_alter_user_email_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('email_id', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('poster_path', models.CharField(max_length=100)),
                ('original_title', models.CharField(max_length=100)),
                ('vote_average', models.CharField(max_length=100)),
            ],
        ),
    ]
