# Generated by Django 3.2.20 on 2023-07-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0003_favorites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(max_length=40)),
                ('poster_path', models.CharField(max_length=100)),
                ('original_title', models.CharField(max_length=100)),
                ('vote_average', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
